---
- include: "romana_kube_np.yml"
  become: true
  become_user: root

- include: "service_configs_{{ ansible_service_mgr }}.yml"
  become: true
  become_user: root

- name: Start services
  service: name="{{ item }}" state="started"
  with_items:
    - romana-kube-np
  become: true
  become_user: root

- name: Install romana tool
  template: src="../cmd/romana.k8s" dest="{{ romana_bin_dir }}/romana" mode=0775
  become: true
  become_user: root

- include: "script.yml"
- include: "demo.yml"
