---
- name: Write Calico cni config
  template:
    src: "cni-calico.conf.j2"
    dest: "/etc/cni/net.d/10-calico.conf"
    owner: kube
  when: kube_network_plugin == "calico"

- name: write the kubecfg (auth) file for kubelet
  template: src=node-kubeconfig.yaml.j2 dest={{ kube_config_dir }}/node-kubeconfig.yaml backup=yes
  notify:
    - restart kubelet

- name: Write proxy manifest
  template:
    src: manifests/kube-proxy.manifest.j2
    dest: "{{ kube_manifest_dir }}/kube-proxy.manifest"

- include: service.yml
  when: not containers_only|default(false)

- include: container.yml
  when: containers_only|default(false)
