#
# Default romana configuration file.
# please move it to ~/.romana.yaml
#
RootURL: "http://{{ romana_master_ip }}"
RootPort: 9600
LogFile: "/var/tmp/romana.log"
Format: "table" # options are table/json 
Platform: "kubernetes"
Verbose: false
