---
- name: Install config file
  template:
    src: "config/romana.cnf.yml"
    dest: "{{romana_etc_dir}}"
    mode: 0644

# RedHat
- name: CNI config file
  template: src="cni/romana-k8s-network" dest="/etc/cni/net.d/10-romana.conf"

- name: Extra configuration for docker service
  file: path="/etc/systemd/system/docker.service.d" state="directory" owner="root" group="root"

- name: Override ExecStart to add bridge IP option
  template: src="systemd/docker_with_bip.conf" dest="/etc/systemd/system/docker.service.d/docker_with_bip.conf"

# Debian
- name: Add docker defaults file to add bridge IP option
  template: src="upstart/defaults_docker" dest="/etc/default/docker"

