---
- name: Install packages requirements on nodes
  action:
    module: "{{ansible_pkg_mgr}}"
    name: "{{item}}"
    state: latest
  with_items: "{{romana_node_pkgs | default([])}}" 

- name: Set docker daemon options
  template:
    src: docker
    dest: "/etc/default/docker"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart docker

- name: Write docker.service systemd file
  template:
    src: systemd-docker.service
    dest: /lib/systemd/system/docker.service
  notify: restart docker
  when: ansible_service_mgr == "systemd" and ansible_os_family != "CoreOS"

- name: Check for nsenter
  stat: path="/usr/bin/nsenter"
  register: ns

- name: Install nsenter
  command: rsync -piu "{{ local_release_dir }}/romana/bin/romana-nsenter" "{{ bin_dir }}/nsenter"
  when: not ns.stat.exists

- name: Install romana cni bin
  command: rsync -piu "{{ local_release_dir }}/romana/bin/romana-cni" "/opt/cni/bin/romana"
  changed_when: false

- name: Install romana agent binary
  command: rsync -piu "{{ local_release_dir }}/romana/bin/romana-agent"  "{{ bin_dir }}/agent"
  changed_when: false

- name: Install romana-kube-agent binary
  command: rsync -piu "{{ local_release_dir }}/romana/bin/romana-kube-agent"  "{{ bin_dir }}/romana-kube-agent"
  changed_when: false

- name: Install romana-agent systemd unit
  template:
    src: "systemd/romana-agent.service"
    dest: "/usr/lib/systemd/system/romana-agent.service"
  notify: restart romana-agent
  when: ansible_service_mgr == "systemd"

- name: Install romana-kube-agent systemd unit
  template:
    src: "systemd/romana-kube-agent.service"
    dest: "/usr/lib/systemd/system/romana-kube-agent.service"
  notify: restart romana-kube-agent
  when: ansible_service_mgr == "systemd"

- name: Install romana-agent upstart service
  template:
    src: "upstart/romana-agent.conf"
    dest: "/etc/init/romana-agent.conf"
  notify: restart romana-agent
  when: ansible_service_mgr == "upstart"

- name: Install romana-kube-agent upstart service
  template:
    src: "upstart/romana-kube-agent.conf"
    dest: "/etc/init/romana-kube-agent.conf"
  notify: restart romana-kube-agent
  when: ansible_service_mgr == "upstart"

