---
- name: Ensure install path exists
  file: path="{{item}}" state=directory
  with_items:
    - "{{romana_lib_dir}}"
    - "{{romana_etc_dir}}"

- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution|lower }}-{{ ansible_distribution_version|lower|replace('/', '_') }}.yml"
      - "{{ ansible_distribution|lower }}-{{ ansible_distribution_release }}.yml"
      - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version|lower|replace('/', '_') }}.yml"
      - "{{ ansible_distribution|lower }}.yml"
      - "{{ ansible_os_family|lower }}.yml"
      - defaults.yml
      paths:
      - ../vars
      skip: true

- include: "{{item}}"
  with_items:
    - install-master.yml
    - mariadb.yml
  when: inventory_hostname == groups['kube-master'][0]

- include: install-node.yml
  when: inventory_hostname in groups['kube-node']

- name: Ensure romana-agent is running
  service:
    name: romana-agent
    state: started
