---
- name: Install other service configurations
  template: src="upstart/{{ item }}" dest="/etc/init/{{ item }}"
  with_items:
    - romana-topology.conf
    - romana-tenant.conf
    - romana-ipam.conf
