---
- include: "romana_kube_agent.yml"
  become: true
  become_user: root

- include: "{{ item }}"
  with_first_found:
    - files: 
      - "packages_{{ ansible_distribution|lower }}_{{ ansible_distribution_release|lower }}.yml"
      - "packages_{{ ansible_distribution|lower }}.yml"
      - "packages_{{ ansible_os_family|lower }}.yml"
      skip: true
  become: true
  become_user: root

- include: "service_configs_{{ ansible_service_mgr }}.yml"
  become: true
  become_user: root

- name: Start services
  service: name="{{ item }}" state="started"
  with_items:
    - romana-kube-agent
  become: true
  become_user: root
